env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb
  - plugin:react/recommended
  - plugin:react-hooks/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: 
  import/extensions: 0
  import/no-unresolved: 0
  no-console: 0
  react/react-in-jsx-scope: 0
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
